### ISSUE TITLE
about main.py

### ISSUE THREAD

**Issue by WeiPeng797** [sang9390/An-Improved-Point-Level-Supervision-Method-for-TAL#1]
Thank you for your outstanding work. I want to train this model by myself. Could you please provide the main.py file of the model? I tried to use the  main.py in LACP, but an error was reported as follows:

Traceback (most recent call last):
  File "E:\swp\An-Improved-Point-Level-Supervision-Method-for-TAL-main\main.py", line 1607, in <module>
    train(net, config, loader_iter, optimizer, criterion, logger, step)
  File "E:\swp\An-Improved-Point-Level-Supervision-Method-for-TAL-main\main.py", line 836, in train
    cost, loss = criterion(vid_score, cas_sigmoid_fuse, features, stored_info, _label, _point_anno, step,
  File "D:\anaconda3\envs\swp\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\swp\An-Improved-Point-Level-Supervision-Method-for-TAL-main\main.py", line 633, in forward
    if sum(sum(bkg_seed_001)) == 0:
  File "D:\anaconda3\envs\swp\lib\site-packages\torch\_tensor.py", line 723, in __iter__
    raise TypeError('iteration over a 0-d tensor')
TypeError: iteration over a 0-d tensor

**Comment by sang9390** [comment]
hello. Thank you for your interest.

We will be able to add code for learning as soon as possible.

If you want to implement it yourself:

  1. Add background point annotation
  2. LACP data loader modifications
  3. Add loss function

Three tasks are required.
